### ISSUE TITLE
pdf files not associated with sioyek

### ISSUE THREAD

**Issue by smidm** [flathub/com.github.ahrm.sioyek#2]
I can see that the: `/var/lib/flatpak/exports/share/applications/com.github.ahrm.sioyek.desktop` contains `MimeType=application/pdf` line, but I can't open pdf files in Gnome Files with Sioyek. It is neither in "Recommended Applications" nor in "View All Applications".

OS: Fedora 35

**Comment by nbenitez** [comment]
Forgot to close this. This was fixed since 1.4.0fl1
