### ISSUE TITLE
cant theme sioyek flatpak 

### ISSUE THREAD

**Issue by barcell1** [flathub/com.github.ahrm.sioyek#24]
TRied theme sioyek , but didnt found prefs_user.config file, and tried to source from other location (~/.config/sioyek/prefs_user.config) but somehow the file dont take effect on sioyek

**Comment by nbenitez** [comment]
The correct path is  `~/.config/sioyek/prefs_user.config` and you would need to create the file.

**Comment by barcell1** [comment]
sorry i mistyped  the path before here , yep i use here ~/.config/sioyek/prefs_user.config 

not working , looks like t didnt read this file since the first command (toggle_custom_color are not executed)
 and when i manually execute the command also dont work 

here is the config prefs_user.config
```
startup_commands toggle_custom_color

# === EVERFOREST HARD DARK THEME === #
background_color               #2E383C  /* Hard Dark Background */

text_highlight_color           #4C3743  /* Dark Soft Red */
visual_mark_color              #272E33  /* Dark Gray */

search_highlight_color         #384B55  /* Dark Blue-Green */
link_highlight_color           #3C4841  /* Dark Muted Green */
synctex_highlight_color        #495156  /* Muted Gray */

highlight_color_a              #4C3743  /* Dark Soft Red */
highlight_color_b              #384B55  /* Dark Blue-Green */
highlight_color_c              #3C4841  /* Dark Muted Green */
highlight_color_d              #414B50  /* Dark Gray */
highlight_color_e              #495156  /* Muted Gray */
highlight_color_f              #4C3743  /* Dark Soft Red */
highlight_color_g              #3C4841  /* Dark Muted Green */

custom_background_color        #2E383C  /* Very Dark Background */
custom_text_color              #D3C6AA  /* Light Cream */

ui_text_color                  #D3C6AA  /* Light Cream */
ui_background_color            #2E383C  /* Dark Gray */
ui_selected_text_color         #D3C6AA  /* Light Cream */
ui_selected_background_color   #374145  /* Dark Gray */

# =============== #
super_fast_search 1
```

**Comment by barcell1** [comment]
running from terminal i found this :

```
QSocketNotifier: Can only be used with threads started with QThread
default_config_path: /app/sioyek/prefs.config
default_keys_path: /app/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /app/etc/xdg/sioyek/prefs_user.config
```

these path dont even exist on my system, running on silverblue

**Comment by nbenitez** [comment]
Yes, you are right there's a bug preventing to access `~/.config/sioyek/prefs_user.config` , the cause is we need to add "--filesystem=xdg-config/sioyek" to `finish-args` of our `com.github.ahrm.sioyek.yaml` file, will do that in a following release.

As a workaround, you can launch Sioyek like below and it'll read  your `~/.config/sioyek/prefs_user.config` file
:
`flatpak run --filesystem=xdg-config/sioyek com.github.ahrm.sioyek your_file.pdf`
