### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by DorianRudolph** [flathub/com.github.ahrm.sioyek#5]
I have `QT_QPA_PLATFORM=wayland` on my system, which causes the flatpak to fail (`qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`). Could this be related to this line? https://github.com/flathub/com.github.ahrm.sioyek/blob/53478f40fcd6c4c70830aa8450fb77a0eddc1d80/com.github.ahrm.sioyek.yaml#L19
It seems wayland is intentionally disabled. Is this still necessary? The latest version of sioyek seems to work fine on wayland.

**Comment by nbenitez** [comment]
I opened #6 to test it.

**Comment by nbenitez** [comment]
Forgot to close this. Sioyek is using wayland since 1.4.0

thanks
